spring:
  dubbo:
    application:
      name: user-provider
    registry:
      address: zookeeper://127.0.0.1:2181
    protocol:
      name: dubbo
      port: 20880
    scan: org.chen.service.impl
    monitor:
      protocol: registry
server:
  port: 9001