spring:
  dubbo:
    application:
      name: user-consumer
    registry:
      address: zookeeper://127.0.0.1:2181
    scan: org.chen.controller
    monitor:
      protocol: registry
server:
  port: 9002
swagger:
  enable: true
